
apiVersion: v1
kind: List
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: alice
  spec:
    selector:
      app: alice
    ports:
    - name: "10001"
      port: 10001
      targetPort: 10001
    - name: "10002"
      port: 10002
      targetPort: 10002
    - name: "10003"
      port: 10003
      targetPort: 10003
    - name: "10004"
      port: 10004
      targetPort: 10004
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: alice
    labels:
      app: alice
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: alice
    strategy:
      type: Recreate
      rollingUpdate: null
    template:
      metadata:
        labels:
          app: alice
      spec:
        hostname: alice
        containers:
        - name: cordapp
          image: kirito37/corda4.3_image
          resources:
            limits:
              memory: "5Gi"
            requests:
              memory: "3Gi"
          ports:
            - containerPort: 10001
            - containerPort: 10002
            - containerPort: 10003
            - containerPort: 10004
          volumeMounts:
          - name: node-config
            mountPath: "/app/node.conf"
            subPath: "node.conf"
            readOnly: true
          - name: node-config
            mountPath: "/app/network-parameters"
            subPath: "network-parameters"
            readOnly: true
          - name: node-log4j
            mountPath: "/app/logs/log4j2.xml"
            subPath: "log4j2.xml"
            readOnly: false
          - name: node-certificates
            mountPath: "/app/certificates"
            readOnly: true
          - name: additional-node-infos
            mountPath: "/app/additional-node-infos"
            readOnly: false
          - name: cordapps
            mountPath: "/app/cordapps/membership-service-1.0.jar"
            subPath: "membership-service-1.0.jar"
            readOnly: true
          - name: cordapps-mem
            mountPath: "/app/cordapps/membership-service-2.0.jar"
            subPath: "membership-service-1.0.jar"
            readOnly: true
          - name: cordapps-mem
            mountPath: "/app/cordapps/membership-service-contracts-and-states-1.0.jar"
            subPath: "membership-service-contracts-and-states-1.0.jar"
            readOnly: true
          - name: cordapps-state-contract
            mountPath: "/app/cordapps/membership-service-contracts-and-states-2.0.jar"
            subPath: "membership-service-contracts-and-states-1.0.jar"
            readOnly: true
          - name: cordapps-app
            mountPath: "/app/cordapps/ping-pong-0.1.jar"
            subPath: "ping-pong-0.1.jar"
            readOnly: true
          - name: cordapps-app-config
            mountPath: "/app/cordapps/config/membership-service.conf"
            subPath: "membership-service.conf"
            readOnly: true
          livenessProbe:
            tcpSocket:
              port: 10002
            initialDelaySeconds: 15
            periodSeconds: 20
        volumes:
        - name: node-config
          secret:
            secretName: alice-config
        - name: node-certificates
          secret:
            secretName: alice-keystore
        - name: additional-node-infos
          secret:
            secretName: alice-additional-node-infos
        - name: cordapps
          secret:
            secretName: alice-cordapps
        - name: cordapps-mem
          secret:
            secretName: alice-cordapps-mem
        - name: cordapps-state-contract
          secret:
            secretName: alice-cordapps-state-contract
        - name: cordapps-app-config
          secret:
            secretName: alice-cordapps-app-config
        - name: cordapps-app
          secret:
            secretName: alice-cordapps-app
        - name: node-log4j
          secret:
            secretName: alice-node-log4j
