apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  annotations:
    pv.beta.kubernetes.io/gid: "123"
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/alice"
